### ISSUE TITLE
AnyCPU and 32bit preference

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.Api#13]
Currently we have seem to have an issue with the bitness of the library. The target is `AnyCPU` (which is the default for .NET 4.x). However, the `32bit preferred` is also set (which is also a default).

This effectively makes the library `x86` (i.e. 32bit).

We want to change that the library will be
* either `x64` only
* or `AnyCPU` without 32bit preference

See [What AnyCPU Really Means As Of .NET 4.5 and Visual Studio 11](http://blogs.microsoft.co.il/sasha/2012/04/04/what-anycpu-really-means-as-of-net-45-and-visual-studio-11/)

**Comment by dfch** [comment]
@rufer7 quick side question: when looking at these settings, I observed that the CodeContracts for this project are not enabled and not equal to the settings as in our other projects (should read `Standard Contract Requires` for both `Debug` and `Release`). Is this intended? maybe you can give a quick reply to this?

![image](https://cloud.githubusercontent.com/assets/8310360/16719131/609012d8-4727-11e6-8655-eec45a8b6aa5.png)

![image](https://cloud.githubusercontent.com/assets/8310360/16719135/70bb3b7e-4727-11e6-8bfb-00974a9a79eb.png)

**Comment by dfch** [comment]
I checked the setting for the 32bit preference and it is **disabled**:

![image](https://cloud.githubusercontent.com/assets/8310360/16719177/ee29eaec-4727-11e6-8b44-cfb28ff33468.png)

**Comment by rufer7** [comment]
@dfch no this is not intemded. Please align the settings according to the other projects
