### ISSUE TITLE
Change namespace in services reference to actual type of service

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.Api#2]
Currently the namespace of the service reference is set to:
* `biz.dfch.CS.Appclusive.Api.Core` 
* `biz.dfch.CS.Appclusive.Api.Diagnostics`

But the actual namespace is 
* `biz.dfch.CS.Appclusive.Core.OdataServices.Core` 
* `biz.dfch.CS.Appclusive.Core.OdataServices.Diagnostics`

Therefore type mappers are used inside the service reference (see `protected global::System.Type ResolveTypeFromName(string typeName)`).

In order to avoid this and to avoid manual type conversion such as when calling OData actions (see [Using ODATA Actions via PowerShell](http://d-fens.ch/2014/08/14/nobrainer-using-odata-actions-via-powershell/) `Replace()`) we should use the *real* types instead.

This will affect the [PoSH Client module](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client).

@rufer7 what is your view on this?

**Comment by rufer7** [comment]
From my point of view we should do that. As sooner as better so we don't have to change too many lines in the POsH Client module

**Comment by rufer7** [comment]
As discussed today with @dfch the namespace will stay as it is.
