### ISSUE TITLE
Replace JSON constructs with classes from Contracts

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Appclusive.Api#3]

**Comment by dfch** [comment]
* we have included `biz.dfch.CS.Appclusive.Contracts` in the assembly for a while but this does not seem to fix the issue we have
* I think we have to include the Contracts.dll into the PoSH `biz.dfch.PS.Appclusive.Client` module so the types are available

@rufer7 your opinion on that? if you agree we should close this issue and create it in the client repo

**Comment by rufer7** [comment]
@dfch did we include it? I assumed including it didn't work!?

**Comment by dfch** [comment]
It is included. But the reference is not transitive as it is not visible *outside* the `Api` assembly but only usable from inside the assembly that includes it as a reference.

Therefore I suggest to simply include the `Contracts` assembly in `biz.dfch.PS.Appclusive.Client` as well.

**Comment by rufer7** [comment]
I created a new issue in Appclusive.Client to track inclusion of the Appclusive contract assembly there.
