### ISSUE TITLE
Implement Entity level action helper

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.Api#5]
Currently we have entity set level action support via one of the several `InvokeEntitySetAction...` methods which allow you to call action in the following form:

```
POST http://api.example.com/base/Endpoint/EntitySetName/Template
```

Such an action would be defined like this:

``` csharp
builder.Entity<Endpoint>().Collection.Action("Template");
```

We need the same for entities like this:

```
POST http://api.example.com/base/Endpoint/EntitySetName(42L)/Update
```

Such an action would be defined like this:

``` csharp
builder.Entity<Endpoint>().Action("Update");
```

We need versions (with and without input parameters) for the following return types:

* `void`
* SingleResult `<T>` (generic and non-generic)
* EntitySets `IEnumerable<T>()`  (generic and non-generic)

**Comment by afcaJordi** [comment]
- [ ] Methods on element level for Core
- [ ] Methods on element level for Diagnositcs
- [ ] Partial class for Cmp
