### ISSUE TITLE
DataServiceContext must support login via Bearer authorization scheme

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.CS.Appclusive.Api#7]
The `DataServiceContext` must support sending an `Authorization` header with in a `Bearer` scheme which contains the *authentication token*.

Suggestion: whenever the `Credential` property contains a credential with name `Bearer` the password property is considered to be the *authentication token*.

Within the `SendingRequest` event we will add the `Authorization` header with the appropriate value.

It is the sole responsibility of the caller to supply a valid token.

This affects
*  [biz.dfch.PS.Appclusive.Client](https://github.com/dfensgmbh/biz.dfch.PS.Appclusive.Client) 
* and [biz.dfch.CS.Appclusive.UI](https://github.com/dfensgmbh/biz.dfch.CS.Appclusive.UI)

@rufer7 comments?

**Comment by rufer7** [comment]
To set custom headers see [here](https://social.msdn.microsoft.com/Forums/en-US/703faf54-ce30-4f5b-835b-4b9e101c7ed5/dataservicecontextsendingrequest2?forum=adodotnetdataservices)
